version: "3.1"

name: todo_items

services:
  mysql:
    image: mysql
    ports:
      - 3307:3306
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Aa@123456
      - MYSQL_DATABASE=todo_items
    restart: unless-stopped
